name: Deploy Application

on:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  TF_STATE_BUCKET_REGION: us-east-1
  TF_LOCK_TABLE: terraform-lock
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=$TF_STATE_BUCKET_NAME" \
            -backend-config="region=$TF_STATE_BUCKET_REGION" \
            -backend-config="dynamodb_table=$TF_LOCK_TABLE" \
            -backend-config="encrypt=true"
        working-directory: ./terraform

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="region=$AWS_REGION" \
            -var="public_key=$PUBLIC_SSH_KEY" \
            -var="private_key=$PRIVATE_SSH_KEY" \
            -var="key_name=deployer-key" \
            -out=PLAN
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve PLAN
        working-directory: ./terraform

  deploy-app:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
           terraform_wrapper: false  

      - name: Get Public IP
        id: ip
        run: |
          cd terraform
          IP=$(terraform output -raw instance_public_ip)
          echo "PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Deploy Applications
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
          script: |
            # Create app directory
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app
            
            # Create Docker Compose file
            cat <<EOT > docker-compose.yml
            version: '3.8'
            services:
              react-app:
                image: migara37/community-client:latest
                ports:
                  - "80:3000"
                restart: always
                
              flask-app:
                image: migara37/community-server:latest
                ports:
                  - "5000:5000"
                restart: always
            EOT
            
            # Pull and run containers
            docker-compose down
            docker-compose pull
            docker-compose up -d