name: Build Docker Images

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build images
        run: 
          docker build -f ./client/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/community-client:latest 
          docker build -f ./server/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME}}/community-server:latest
      - name: publish images    
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_TOKEN}}
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/community-client:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/community-server:latest
  